env:
  browser: true
  es6: true
  node: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {
  no-console: 0
}
plugins:
  # https://github.com/babel/eslint-plugin-babel
  - babel

# https://github.com/babel/babel-eslint
parser: babel-eslint

