env:  
  es6: true
  node: true
extends:
  - airbnb-base
rules: {
  no-console: 0
}
plugins:
  # https://github.com/babel/eslint-plugin-babel
  - babel

# https://github.com/babel/babel-eslint
parser: babel-eslint

