language: node_js

node_js:
  - node

env:
  global:
    - CC_TEST_REPORTER_ID=<903c7d2da034be54f5af6ac92363bd120a1d713bc2e5ef387e5211dc9abc6100>

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make lint
  - make test-coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false